---
name: ci

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  cookstyle:
    runs-on: ubuntu-latest
    container:
      image: chef/chefdk:3.14.16
    steps:
      - uses: actions/checkout@v2
      - name: Cookstyle
        run: |
          chef --version
          cookstyle --version
          cookstyle ./

  # Re-enable when available for our enterprise
  # Also add mdl
  # similar to https://github.com/sous-chefs/nodejs/blob/main/.github/workflows/ci.yml
  #yamllint:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Check out code
  #      uses: actions/checkout@v2
  #    - name: Run yaml Lint
  #      uses: actionshub/yamllint@main
